### ISSUE TITLE
Pre-Built binary not working on CentOS 8 Stream

### ISSUE THREAD

**Issue by AmazingPP** [bbannier/zeek-language-server#12]
```
[Error - 下午7:44:01] Connection to server is erroring. Shutting down server. 
/usr/local/bin/zeek-language-server-x86_64-unknown-linux-gnu: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/zeek-language-server-x86_64-unknown-linux-gnu)
```
Shold we need to down the `glibc` requirement ?

**Comment by bbannier** [comment]
I have merged a patch so the next release artifacts we build should work with `GLIBC_2.28` as well. I have not yet cut a release though as I was hoping we could get a fix in for e.g., #14 before that.
