### ISSUE TITLE
Syntax highlighting incorrectly parses `subnet` into `pattern`

### ISSUE THREAD

**Issue by AmazingPP** [bbannier/zeek-language-server#14]
Triggered when two `subnet`s are on the same line.

![image](https://user-images.githubusercontent.com/30434507/180609321-e37a98e4-e30f-4e83-9aac-fec66c4d3f04.png)

**Comment by bbannier** [comment]
The current syntax doesn't have any support for subnets, but it does for addresses and regexps, so this seems to be expected. Could you look into whether we could add support for them @AmazingPP? I am not sure if that can interfere with other hightlighting, but I'd suspect we might be fine for the case of greedy matching (not sure what vscode does though).

**Comment by AmazingPP** [comment]
Yes, I'm going to add subnet support for syntax highlighting.I will create PR after implement and testing.

TextMate grammar supports greedy matching.
