### ISSUE TITLE
0.35.0 Upgrade Broke Formatting

### ISSUE THREAD

**Issue by keithjjones** [bbannier/zeek-language-server#218]
The "Format Document" option disappeared from my Visual Code right click menu when I installed 0.35.0.  I downgraded to 0.34.0 and it works fine.  zeek-format is in my path on my Macbook running on an M2.  0.35.0 acts like it cannot find it even though 0.34.0 can.

**Comment by bbannier** [comment]
Not sure what to do here, this works well for me.
<img width="747" alt="Screenshot 2023-12-14 at 9 42 36 PM" src="https://github.com/bbannier/zeek-language-server/assets/324957/d7b74aab-177b-4f79-be9d-b30e7ffea0c8">

**Comment by bbannier** [comment]
The vscode extension for 0.35.0 had an issue downloading the platform-dependent server binary. This might have been related, but it is impossible to tell whether that was the issue here from the info given. I put out a 0.36.0 fixing the download.

**Comment by keithjjones** [comment]
Installing 0.36.0 fixed it.  Thanks.
