### ISSUE TITLE
Support custom `zeek-config` and `zeek` executable path

### ISSUE THREAD

**Issue by AmazingPP** [bbannier/zeek-language-server#34]
When I develop Zeek plugins, I don't install plugins into Zeek in the system directory. 

So when I write a Zeek script to call the new bif function in the plugin, lsp will report `undefined id` error, I think we need a configuration to customize the path of `zeek` and `zeek-config` executables.

I can try to implement it.

**Comment by bbannier** [comment]
We need `zeek-config` to [discover prefixes containing system source files](https://github.com/bbannier/zeek-language-server/blob/cdea82efd9e711a10b86688f1651c06f6cec0ff2/src/zeek.rs#L48-L60) and `zeek` to check whether it emits additional diagnostics. We could probably allow users to configure prefixes via configuration (this could also allow users to set up completion on e.g., Windows if they manage to extract the files); AFAIR the check step with `zeek` is already optional.

The way to work around installation into non-standard prefixes is usually to set up a `PATH` containing the binaries which works well if the user sets up the way the server is started; we could probably add an option to the vscode extension which allows injecting some `PATH` where `zeek` and `zeek-config` can be found.
