### ISSUE TITLE
No type inferred for local o = c$orig and no completions

### ISSUE THREAD

**Issue by awelzel** [bbannier/zeek-language-server#66]
Hey - follow up for #60 / #65

With the following snippet, one would expect to a) o being resolved with type `endpoints` and `o$si` providing completions for size. Neither works.
```
event x(c: connection) {
  local o = c$orig;
  print o$si...
}
```

As a crutch, explicitly adding `local o: endpoint` helps out.

**Comment by bbannier** [comment]
Reopening as the completion part is still not working.
